plugins {
    id 'java'
}

group = 'com.sdmine'
version = '1.0.0'

sourceCompatibility = '17'
targetCompatibility = '17'

repositories {
    mavenCentral()
    maven {
        name = 'papermc-repo'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'
}

jar {
    archiveBaseName.set('ElementalCoreWeaponSystem')
    archiveVersion.set('1.0.0')
}

compileJava {
    options.encoding = 'UTF-8'
}
